// <auto-generated />
using System;
using BlazorUserManagerApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorUserManagerApp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "1",
                            Name = "Supervisor",
                            NormalizedName = "SUPERVISOR"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Operator",
                            NormalizedName = "OPERATOR"
                        },
                        new
                        {
                            Id = "3",
                            Name = "WhithoutRole",
                            NormalizedName = "WHITHOUTROLE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BlazorUserManagerApp.Models.Employee", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ChangePaswword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastPasswordChange")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Salary")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Employee");

                    b.HasData(
                        new
                        {
                            Id = "-1041728855",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f5f629cd-13a0-4ed1-918e-74b9a5931ee8",
                            Email = "Citlalli.Koch@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "(783) 768-5183 x9700",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "da2006eb-0cac-44da-9a0f-2fe7703ee958",
                            TwoFactorEnabled = false,
                            UserName = "Annabelle75",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/252.jpg",
                            ChangePaswword = true,
                            FullName = "Carley Yundt",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 52251m,
                            Type = 3
                        },
                        new
                        {
                            Id = "-1733199110",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3062f40a-9df1-42c9-b520-5e08950a611d",
                            Email = "Cole_Okuneva@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "1-892-399-6145 x753",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0ffed20c-7791-47cf-959e-bb0f9721390b",
                            TwoFactorEnabled = false,
                            UserName = "Justice68",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/159.jpg",
                            ChangePaswword = true,
                            FullName = "Alexander Schneider",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 33170m,
                            Type = 3
                        },
                        new
                        {
                            Id = "-687822296",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "52225dcc-0f1d-4d7b-ae25-84d45685ee41",
                            Email = "Tobin.Wiza@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "347-663-5599 x829",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "55ceee0b-7639-4743-9cf7-88168a79aff5",
                            TwoFactorEnabled = false,
                            UserName = "Sibyl98",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/900.jpg",
                            ChangePaswword = true,
                            FullName = "Clement Balistreri",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 65941m,
                            Type = 0
                        },
                        new
                        {
                            Id = "-30157812",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1568b0d8-3f64-43f9-bc9f-e2c547db909c",
                            Email = "Darrell44@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "906-416-5642",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9ab58ef0-bb6c-400f-a92f-774dd33e3fdb",
                            TwoFactorEnabled = false,
                            UserName = "Anne1",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/662.jpg",
                            ChangePaswword = true,
                            FullName = "Coby Vandervort",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 56727m,
                            Type = 3
                        },
                        new
                        {
                            Id = "-1791425608",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5b9e2a66-2beb-4631-a14e-65d49bcad20e",
                            Email = "Gerry44@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "(600) 507-6469",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "76ea199e-e54d-4d8c-ad5e-9cd8f9adf03a",
                            TwoFactorEnabled = false,
                            UserName = "Jeffery51",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/366.jpg",
                            ChangePaswword = true,
                            FullName = "Vernie Dicki",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 79483m,
                            Type = 3
                        },
                        new
                        {
                            Id = "-1840598733",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8fc4bdb1-d209-4b93-951a-02a54736a301",
                            Email = "Jasen_McClure77@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "(420) 553-2414 x3905",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3e0d8c99-4ba2-4695-a2c0-917d98c43d93",
                            TwoFactorEnabled = false,
                            UserName = "Ryan_Hodkiewicz41",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/415.jpg",
                            ChangePaswword = true,
                            FullName = "Helen Osinski",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 36941m,
                            Type = 2
                        },
                        new
                        {
                            Id = "-894282017",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0347e9f8-05eb-433d-b812-0624ec122445",
                            Email = "Gretchen.Hagenes4@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "(268) 472-2301 x1395",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "782e6f32-2329-46e0-a6e0-c1a834a735d8",
                            TwoFactorEnabled = false,
                            UserName = "Dorothy_Pfeffer90",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/514.jpg",
                            ChangePaswword = true,
                            FullName = "Matteo Schulist",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 93358m,
                            Type = 2
                        },
                        new
                        {
                            Id = "1996961046",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f4dad82b-c7c4-4810-802f-1e6a19bf13e9",
                            Email = "Hertha_Torp14@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "248.533.5750 x2645",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ed8db82b-4ec9-4b4e-a4ad-cfc90bb9fc85",
                            TwoFactorEnabled = false,
                            UserName = "Alanis31",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/468.jpg",
                            ChangePaswword = true,
                            FullName = "Velma Swaniawski",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 52072m,
                            Type = 3
                        },
                        new
                        {
                            Id = "-1583939571",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "729b79fb-0660-4974-8191-3975b753ea42",
                            Email = "Rupert.Hermann5@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "(591) 515-8994 x2421",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "507c5268-fb70-4b7f-8b51-d2306b0a0134",
                            TwoFactorEnabled = false,
                            UserName = "Marjorie69",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/105.jpg",
                            ChangePaswword = true,
                            FullName = "Alvera Mills",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 55100m,
                            Type = 0
                        },
                        new
                        {
                            Id = "1901365618",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c0b7b494-3a18-4152-a413-29778c1d8110",
                            Email = "Donald_Romaguera@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "(402) 499-1437",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d8dc48b4-a0ae-499b-b658-2ad6f0caa0fe",
                            TwoFactorEnabled = false,
                            UserName = "Zaria_Cruickshank",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/13.jpg",
                            ChangePaswword = true,
                            FullName = "Brain Tillman",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 91622m,
                            Type = 2
                        },
                        new
                        {
                            Id = "1169615930",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "77d3f377-77dc-4dec-a982-18645e71a7b3",
                            Email = "Lester_Wunsch92@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "(352) 259-9836 x738",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cf50800c-4213-4112-ba23-ae1b4a0a712f",
                            TwoFactorEnabled = false,
                            UserName = "Darrick_Mraz86",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/23.jpg",
                            ChangePaswword = true,
                            FullName = "Mittie Grant",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 64444m,
                            Type = 3
                        },
                        new
                        {
                            Id = "1421866959",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c99a4d6d-5629-40fd-b877-c2ee060293dd",
                            Email = "Ezra.Gutkowski@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "539-899-3095",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "53a473ea-265b-4d19-860a-bec527922874",
                            TwoFactorEnabled = false,
                            UserName = "Lamar13",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/519.jpg",
                            ChangePaswword = true,
                            FullName = "Ernestine Christiansen",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 91036m,
                            Type = 2
                        },
                        new
                        {
                            Id = "1116895551",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c8ada07d-7439-4dcb-88d5-2c306c8b909e",
                            Email = "Casimer.Streich@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "(425) 562-0860",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1113e2ee-cabf-4b10-89eb-8e9b9ddab034",
                            TwoFactorEnabled = false,
                            UserName = "Elvie_Donnelly53",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/947.jpg",
                            ChangePaswword = true,
                            FullName = "Zackary Schmidt",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 95770m,
                            Type = 0
                        },
                        new
                        {
                            Id = "249140173",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fdd683b4-ca89-4707-9116-f1073e5fc31a",
                            Email = "Earlene.Hackett@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "(509) 689-5353 x188",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "64173ecd-98f8-48cc-9f2f-2d7efba9dff5",
                            TwoFactorEnabled = false,
                            UserName = "Alice91",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/880.jpg",
                            ChangePaswword = true,
                            FullName = "Kacie Block",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 50570m,
                            Type = 0
                        },
                        new
                        {
                            Id = "1746114836",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3bb8b26d-245a-4e35-974c-db9b5cb186e3",
                            Email = "Jaylon48@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "1-377-965-6144",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "da9c7b32-843b-49ac-ae9f-8cc2087e5f68",
                            TwoFactorEnabled = false,
                            UserName = "Louvenia.Halvorson84",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1157.jpg",
                            ChangePaswword = true,
                            FullName = "Michelle Langosh",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 67545m,
                            Type = 3
                        },
                        new
                        {
                            Id = "-1605068460",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e44f4b4a-b5dd-4c46-879f-39faf6cc7337",
                            Email = "Gerardo_Satterfield97@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "307-969-4001",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "df5ee9ad-7bb0-426e-abbe-848386173f9d",
                            TwoFactorEnabled = false,
                            UserName = "Alejandra31",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/652.jpg",
                            ChangePaswword = true,
                            FullName = "Adela DuBuque",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 85074m,
                            Type = 1
                        },
                        new
                        {
                            Id = "112133638",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "244ba56d-dea9-431c-a54b-7e05a5fef751",
                            Email = "Sam66@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "1-627-419-4121",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c897319c-2afb-4187-b56c-bfd39ddef271",
                            TwoFactorEnabled = false,
                            UserName = "Tyler86",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/839.jpg",
                            ChangePaswword = true,
                            FullName = "Xander Stark",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 99655m,
                            Type = 2
                        },
                        new
                        {
                            Id = "-1325717676",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "12f17541-cd8d-4407-904f-7bd46d36eee2",
                            Email = "Jesse59@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "1-267-569-6576",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "844cb6bc-082f-4665-8c37-fd3378036c80",
                            TwoFactorEnabled = false,
                            UserName = "Catharine_Rolfson61",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/379.jpg",
                            ChangePaswword = true,
                            FullName = "Zola Quitzon",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 92898m,
                            Type = 3
                        },
                        new
                        {
                            Id = "1654946659",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fcaef1f7-d307-479e-ba5a-65c306156a0c",
                            Email = "Ramon.Friesen22@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "1-649-924-6505",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "80455730-465b-4044-ac28-4f80823243bf",
                            TwoFactorEnabled = false,
                            UserName = "Kyle_Wisoky",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/765.jpg",
                            ChangePaswword = true,
                            FullName = "Alan Zboncak",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 59607m,
                            Type = 3
                        },
                        new
                        {
                            Id = "-1539967329",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "55449886-3499-4aaf-a93b-d512e2d42816",
                            Email = "Kariane.Witting@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "(516) 688-2295",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7db3de35-8173-4f1d-9587-37b7db071ef6",
                            TwoFactorEnabled = false,
                            UserName = "Nina_Deckow",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/329.jpg",
                            ChangePaswword = true,
                            FullName = "Timmy Cummerata",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 71233m,
                            Type = 0
                        },
                        new
                        {
                            Id = "81077800",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b4283721-2bf2-4211-8108-1c2d6d8ee14e",
                            Email = "Felton.Bartoletti@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "1-657-591-4297 x643",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6f998fb3-9e22-4def-8c07-74f386a35016",
                            TwoFactorEnabled = false,
                            UserName = "Triston_Robel",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/503.jpg",
                            ChangePaswword = true,
                            FullName = "Eric Gislason",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 85782m,
                            Type = 1
                        },
                        new
                        {
                            Id = "-1064855082",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1da29396-de72-47c8-83ea-3ba7a82f3f6e",
                            Email = "Alexandra88@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "380.517.2255 x7109",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c14c35d5-94bc-486a-9e11-3f5385d311c0",
                            TwoFactorEnabled = false,
                            UserName = "Katrina_Koch53",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/354.jpg",
                            ChangePaswword = true,
                            FullName = "Ernestine Mills",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 92344m,
                            Type = 2
                        },
                        new
                        {
                            Id = "-2022590128",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1b59eaca-ec25-4ed4-80ac-875ed0f99c01",
                            Email = "Norwood_Johns@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "716-566-8231",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b0794b3c-6343-4e27-88e3-a2c6dc636fdc",
                            TwoFactorEnabled = false,
                            UserName = "Elias_Renner",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1045.jpg",
                            ChangePaswword = true,
                            FullName = "Norbert Doyle",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 35409m,
                            Type = 2
                        },
                        new
                        {
                            Id = "-1380571505",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "798f1556-ed62-4d0b-a91e-13cdee1e8400",
                            Email = "Clair41@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "1-356-491-2834 x2235",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "435a33f6-00ec-43a8-9ca3-5dbbd23a2c26",
                            TwoFactorEnabled = false,
                            UserName = "Gregg.Waters68",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/992.jpg",
                            ChangePaswword = true,
                            FullName = "Geovanni Harvey",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 58839m,
                            Type = 3
                        },
                        new
                        {
                            Id = "717878175",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "da151093-facf-46cb-8524-e34242e8adb2",
                            Email = "Isabella53@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "1-459-459-0795",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "aa5e3ef1-5197-4a6e-8266-140fa58d43e0",
                            TwoFactorEnabled = false,
                            UserName = "Veda.Schamberger74",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/568.jpg",
                            ChangePaswword = true,
                            FullName = "Anibal Koss",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 33936m,
                            Type = 2
                        },
                        new
                        {
                            Id = "343730503",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1aa5bf8e-520d-49fb-9f61-f7ade70f1241",
                            Email = "Mohammed.Champlin35@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "495-522-6579",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bec47097-a8a8-4287-9842-1f44360f1bf0",
                            TwoFactorEnabled = false,
                            UserName = "Kathryn_Rau23",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/215.jpg",
                            ChangePaswword = true,
                            FullName = "Sharon Little",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 78385m,
                            Type = 0
                        },
                        new
                        {
                            Id = "-666694766",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5be4a987-c13f-471f-b582-c686dece834c",
                            Email = "Berniece.Rempel24@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "743.857.8529 x812",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9dbd47ed-f74f-4769-9fd8-266b498c22db",
                            TwoFactorEnabled = false,
                            UserName = "Earline13",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/485.jpg",
                            ChangePaswword = true,
                            FullName = "Ariel Wisoky",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 85231m,
                            Type = 0
                        },
                        new
                        {
                            Id = "1719016834",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2dafb1ae-91ed-4db4-837d-532b5269f60b",
                            Email = "Lavern22@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "1-240-968-9382 x3947",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a8903ca2-6db0-4951-8604-1ddac8fbcded",
                            TwoFactorEnabled = false,
                            UserName = "Geovanni.Hoeger",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/672.jpg",
                            ChangePaswword = true,
                            FullName = "Ardella Schultz",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 62691m,
                            Type = 3
                        },
                        new
                        {
                            Id = "285144790",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "204b5c45-2dd0-4189-9b85-e9ff637f1de6",
                            Email = "Armani.Pacocha@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "1-480-884-3129",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8ebe40dd-cb66-4282-8594-a1ba74955c9a",
                            TwoFactorEnabled = false,
                            UserName = "Lilyan_Kessler48",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/398.jpg",
                            ChangePaswword = true,
                            FullName = "Gregg O'Reilly",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 61953m,
                            Type = 0
                        },
                        new
                        {
                            Id = "-1556218354",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7529404b-1ca8-4279-a1fc-01f7eb4174d5",
                            Email = "Richard.McGlynn@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "368-328-9441 x39977",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "35bdd05c-52e4-4045-8681-42abbc87fa13",
                            TwoFactorEnabled = false,
                            UserName = "Merlin.Osinski",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/530.jpg",
                            ChangePaswword = true,
                            FullName = "Lawrence Ziemann",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 79453m,
                            Type = 0
                        },
                        new
                        {
                            Id = "-549051341",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e81fa2e9-4fd3-401b-8cdc-c8cace78bc85",
                            Email = "Samara42@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "576-658-9974 x1364",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3898c3f0-2e3e-43f0-8e38-3af4e0b2adfe",
                            TwoFactorEnabled = false,
                            UserName = "Adela.Goldner",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1151.jpg",
                            ChangePaswword = true,
                            FullName = "Ellis Treutel",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 44377m,
                            Type = 0
                        },
                        new
                        {
                            Id = "2019466986",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e325fd02-688f-4925-9a44-7673451736e3",
                            Email = "Preston_Rogahn98@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "1-443-963-0127 x1206",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ab54d76c-2abb-475c-a911-c289c59a88e6",
                            TwoFactorEnabled = false,
                            UserName = "Deja.Thiel",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/383.jpg",
                            ChangePaswword = true,
                            FullName = "Marcellus Langworth",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 38738m,
                            Type = 3
                        },
                        new
                        {
                            Id = "559459875",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "98bf9900-f539-4102-acd5-6539818063a3",
                            Email = "Kyleigh37@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "201-854-7729 x41420",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5d605882-1b90-4fc2-b62d-d54f6c4ba439",
                            TwoFactorEnabled = false,
                            UserName = "Meta42",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/649.jpg",
                            ChangePaswword = true,
                            FullName = "Rafael Weber",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 52106m,
                            Type = 3
                        },
                        new
                        {
                            Id = "1151347690",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dd24b7a7-9ba0-430e-8cdf-18ec32849182",
                            Email = "Lavina_Morar@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "224-959-8132 x6878",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8336f1ed-5991-4072-b4ff-11e7548b2af7",
                            TwoFactorEnabled = false,
                            UserName = "Jon89",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1177.jpg",
                            ChangePaswword = true,
                            FullName = "Rey Waters",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 85651m,
                            Type = 1
                        },
                        new
                        {
                            Id = "192774192",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3480ba3d-f69f-4253-9e57-6757a3e89f12",
                            Email = "Tiana.Jacobson35@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "606.563.4660",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "633499ff-dc7e-4216-84d0-2f22bc181475",
                            TwoFactorEnabled = false,
                            UserName = "Krista85",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/922.jpg",
                            ChangePaswword = true,
                            FullName = "Samir Walker",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 57748m,
                            Type = 0
                        },
                        new
                        {
                            Id = "-609167778",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "73095c21-8ce0-4583-8e90-b8711f1c5646",
                            Email = "Robbie66@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "872.200.3987 x315",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0a058870-74a0-4eab-8fe0-d73488285a0b",
                            TwoFactorEnabled = false,
                            UserName = "Vergie.Weimann48",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/418.jpg",
                            ChangePaswword = true,
                            FullName = "Aliya Witting",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 48568m,
                            Type = 1
                        },
                        new
                        {
                            Id = "-519073023",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "97333606-e47e-4ad4-8c62-4de7cede4518",
                            Email = "June.Brown@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "1-400-397-4849",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ddf19a00-dcf0-42c8-aa40-b226f9309736",
                            TwoFactorEnabled = false,
                            UserName = "Jamison.Kessler22",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/343.jpg",
                            ChangePaswword = true,
                            FullName = "Emie Schowalter",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 85753m,
                            Type = 0
                        },
                        new
                        {
                            Id = "661376552",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3c5fab14-2278-4998-aa3c-94d7498d145e",
                            Email = "Kieran_Sporer70@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "954-914-4447",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c6208f7a-363a-4490-bcc1-f8a92d23faac",
                            TwoFactorEnabled = false,
                            UserName = "Rocio_Murray",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/865.jpg",
                            ChangePaswword = true,
                            FullName = "Dave Kling",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 68744m,
                            Type = 2
                        },
                        new
                        {
                            Id = "1160810117",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fee9a66b-8867-4691-a7e1-b1f098871100",
                            Email = "Elfrieda_Tillman@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "332.847.2436 x68629",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a3825e42-ef7c-4cc5-b6cc-38fc545b0c60",
                            TwoFactorEnabled = false,
                            UserName = "Madelyn.Johnston26",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/132.jpg",
                            ChangePaswword = true,
                            FullName = "Constantin Labadie",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 46454m,
                            Type = 3
                        },
                        new
                        {
                            Id = "788708289",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9bf4c740-d838-465f-8d7b-c1c7bb9d1289",
                            Email = "Berneice73@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "269.401.3725",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fe470d0d-b485-4fee-875a-e5f6aad8d95a",
                            TwoFactorEnabled = false,
                            UserName = "Korbin63",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/736.jpg",
                            ChangePaswword = true,
                            FullName = "Talia Langworth",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 97812m,
                            Type = 1
                        },
                        new
                        {
                            Id = "-8925989",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dface7ac-474b-48ce-b514-71b6ba38b1ab",
                            Email = "Austin.Koss53@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "1-489-543-9729 x778",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ed9c9fd1-9a55-4fca-b356-1e15793748df",
                            TwoFactorEnabled = false,
                            UserName = "Karlie_Cremin",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/202.jpg",
                            ChangePaswword = true,
                            FullName = "Ansley Hansen",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 83617m,
                            Type = 2
                        },
                        new
                        {
                            Id = "-552809776",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b6a4f745-9fb8-410e-b283-862cad0af82d",
                            Email = "Alessandro_Rutherford42@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "812-329-0224 x8716",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b07bee03-41c7-41ff-a053-db8b8d06584c",
                            TwoFactorEnabled = false,
                            UserName = "Bernadine.Braun5",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/304.jpg",
                            ChangePaswword = true,
                            FullName = "Bridie Dibbert",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 38658m,
                            Type = 2
                        },
                        new
                        {
                            Id = "-1202671349",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "833a20df-0357-4e98-86c1-cf0904e091fd",
                            Email = "Ashly50@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "(921) 359-2018",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d6ae4723-e9ef-462e-9971-7a455ee2ac26",
                            TwoFactorEnabled = false,
                            UserName = "Royal_Huel",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/42.jpg",
                            ChangePaswword = true,
                            FullName = "Giuseppe Satterfield",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 88878m,
                            Type = 0
                        },
                        new
                        {
                            Id = "78815829",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9a2dfd5c-5e74-41d2-a68a-1577e8b3789f",
                            Email = "Natalie48@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "(707) 728-0770 x58508",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c222658f-bfcd-4910-bd2e-55ba6fb54bc8",
                            TwoFactorEnabled = false,
                            UserName = "Aiyana12",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/18.jpg",
                            ChangePaswword = true,
                            FullName = "Jairo Gutkowski",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 43836m,
                            Type = 0
                        },
                        new
                        {
                            Id = "-1556712821",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bde0ad31-0d89-4548-8fa1-1bf011d3c816",
                            Email = "Elouise.Kshlerin@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "624-957-1932 x01194",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "57fc7f8c-eec0-46ae-9498-ef52929a7ee0",
                            TwoFactorEnabled = false,
                            UserName = "Theresa.Bartoletti",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/951.jpg",
                            ChangePaswword = true,
                            FullName = "Miller Wilkinson",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 47325m,
                            Type = 0
                        },
                        new
                        {
                            Id = "-1572370794",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fcf2d671-02bb-464a-b378-79ee75b70afa",
                            Email = "Kathryn.Pacocha73@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "800.488.4218",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "92cf7599-d422-4d1b-aeb4-54addb94254c",
                            TwoFactorEnabled = false,
                            UserName = "Brennon.Monahan88",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/911.jpg",
                            ChangePaswword = true,
                            FullName = "Marjorie Sauer",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 53947m,
                            Type = 1
                        },
                        new
                        {
                            Id = "2018019028",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6db286d1-eae2-49ca-a40e-811545f25cbb",
                            Email = "Ray_Gutkowski44@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "827.682.9105",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cbf625de-ccc9-4d84-b1f0-c2ece7e7016c",
                            TwoFactorEnabled = false,
                            UserName = "Hilario10",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/499.jpg",
                            ChangePaswword = true,
                            FullName = "Maud Durgan",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 45593m,
                            Type = 1
                        },
                        new
                        {
                            Id = "-989830954",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b207e01c-9d12-41f4-9739-302509904dbc",
                            Email = "Esmeralda.Lehner0@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "(646) 262-6373 x15249",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b648c30f-7afb-4692-8e7b-1be6c9627cf6",
                            TwoFactorEnabled = false,
                            UserName = "Dion.Carter95",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/852.jpg",
                            ChangePaswword = true,
                            FullName = "Mabel Hane",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 56739m,
                            Type = 1
                        },
                        new
                        {
                            Id = "199212329",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d443e812-f5bf-4f66-b316-3c5b064201d3",
                            Email = "Wiley_Cummerata74@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "258.236.5869 x38499",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "933663d7-2202-42a0-a231-ed76c83ee3cc",
                            TwoFactorEnabled = false,
                            UserName = "Lera79",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1172.jpg",
                            ChangePaswword = true,
                            FullName = "Jeanie Bashirian",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 33691m,
                            Type = 0
                        },
                        new
                        {
                            Id = "494582182",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "af113a88-87a2-4214-b0a9-1354730cf43c",
                            Email = "Berenice_Labadie@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumber = "1-344-843-3582",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5687fc41-d524-46b1-8a5b-027d423294ba",
                            TwoFactorEnabled = false,
                            UserName = "Rigoberto40",
                            Active = true,
                            Avatar = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/123.jpg",
                            ChangePaswword = true,
                            FullName = "Reina Lemke",
                            LastPasswordChange = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 3,
                            Salary = 46086m,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
